name = "ModalLogic"
defaultTargets = ["Fin74"]

[[lean_lib]]
name = "ModalLogic"

[[lean_lib]]
name = "ModalLogicArchive"

[[lean_lib]]
name = "Fin74"

[[require]]
name = "Foundation"
git = "https://github.com/FormalizedFormalLogic/Foundation"
rev = "master"
