module

public import Neighborhood.Hilbert.Logic.«0»
public import Neighborhood.Hilbert.Logic.«1»
public import Neighborhood.Hilbert.Logic.«2»
public import Neighborhood.Hilbert.Logic.«3»
public import Neighborhood.Hilbert.Logic.«4»
public import Neighborhood.Hilbert.Logic.«5»
public import Neighborhood.Hilbert.Logic.«6»
public import Neighborhood.Hilbert.Logic.«7»
public import Neighborhood.Hilbert.Logic.«8»

/-!
# The classical non-normal modal logics between `LogicE` and `LogicEMCNTDB45`

Definitions of the classical modal logics by their Hilbert axiomatisations, each given as the
`Hilbert` system generated by every instance of the named axiom schemes.

Besides `LogicEK`, `LogicEMK`, `LogicEMCK` and `LogicEP`, the logics form a grid: each of the
eight classical bases `E`, `EM`, `EC`, `EN`, `EMC`, `EMN`, `ECN`, `EMCN` is extended by one of
the fifteen axiom combinations of `T`, `D`, `B`, `4`, `5` that axiomatise the fifteen distinct
normal modal logics of the standard cube over `K`: `∅`, `T`, `D`, `B`, `4`, `5`, `TB`, `T4`,
`T5`, `DB`, `D4`, `D5`, `D45`, `45`, `B4`.  Over the weaker classical bases, combinations that
coincide over `K` need not coincide, so all fifteen are taken as primitive definitions.

This file holds the extensions by four and by five of the axioms `M`, `C`, `N`, `T`, `D`, `B`,
`4`, `5`; the extensions by fewer are in `Hilbert/Logic/{0,1,2,3}`, those by six or more in
`Hilbert/Logic/{6,7,8}`.  Every extension by six or more collapses onto one axiomatised by
fewer axioms, as `Logic/Logic/<name>.lean` records.
-/

@[expose] public section

variable {α : Type u}

end
