module

public import Neighborhood.Hilbert.Basic

/-!
# The classical non-normal modal logics between `E` and `ET5`

Definitions of the logics `E`, `EM`, ..., `ET5` by their Hilbert axiomatisations, each given as the
`Hilbert` system generated by every instance of the named axiom schemes, and the two
coincidences of logics with different axiom sets.
-/

@[expose] public section

variable {α : Type u}

/-! ### The weakest logic -/

/-- The weakest classical modal logic, i.e. the Hilbert system with no additional axiom scheme. -/
abbrev E : Logic α := Hilbert ∅

/-! ### Logics generated by a single axiom scheme -/

/-- Every instance of the axiom scheme `M`. -/
abbrev EM.axioms : FormulaSet α := { Axioms.M A B | (A) (B) }

/-- The logic generated by the axiom scheme `M`. -/
abbrev EM : Logic α := Hilbert EM.axioms

instance : (EM (α := α)).HasAxiomM := Hilbert.hasAxiomM_of fun A B => ⟨A, B, rfl⟩

/-- Every instance of the axiom scheme `C`. -/
abbrev EC.axioms : FormulaSet α := { Axioms.C A B | (A) (B) }

/-- The logic generated by the axiom scheme `C`. -/
abbrev EC : Logic α := Hilbert EC.axioms

instance : (EC (α := α)).HasAxiomC := Hilbert.hasAxiomC_of fun A B => ⟨A, B, rfl⟩

/-- The axiom `N`. -/
abbrev EN.axioms : FormulaSet α := {Axioms.N}

/-- The logic generated by the axiom `N`. -/
abbrev EN : Logic α := Hilbert EN.axioms

instance : (EN (α := α)).HasAxiomN := Hilbert.hasAxiomN_of rfl

/-! ### Logics combining `M`, `C`, `N` -/

/-- Every instance of the axiom schemes `M` and `C`. -/
abbrev EMC.axioms : FormulaSet α := EM.axioms ∪ EC.axioms

/-- The logic generated by the axiom schemes `M` and `C`. -/
abbrev EMC : Logic α := Hilbert EMC.axioms

instance : (EMC (α := α)).HasAxiomM := Hilbert.hasAxiomM_of fun A B => Or.inl ⟨A, B, rfl⟩
instance : (EMC (α := α)).HasAxiomC := Hilbert.hasAxiomC_of fun A B => Or.inr ⟨A, B, rfl⟩

/-- Every instance of the axiom scheme `M` together with the axiom `N`. -/
abbrev EMN.axioms : FormulaSet α := EM.axioms ∪ EN.axioms

/-- The logic generated by the axiom scheme `M` together with the axiom `N`. -/
abbrev EMN : Logic α := Hilbert EMN.axioms

instance : (EMN (α := α)).HasAxiomM := Hilbert.hasAxiomM_of fun A B => Or.inl ⟨A, B, rfl⟩
instance : (EMN (α := α)).HasAxiomN := Hilbert.hasAxiomN_of (Or.inr rfl)

/-- Every instance of the axiom scheme `C` together with the axiom `N`. -/
abbrev ECN.axioms : FormulaSet α := EC.axioms ∪ EN.axioms

/-- The logic generated by the axiom scheme `C` together with the axiom `N`. -/
abbrev ECN : Logic α := Hilbert ECN.axioms

instance : (ECN (α := α)).HasAxiomC := Hilbert.hasAxiomC_of fun A B => Or.inl ⟨A, B, rfl⟩
instance : (ECN (α := α)).HasAxiomN := Hilbert.hasAxiomN_of (Or.inr rfl)

/-- Every instance of the axiom schemes `M`, `C` together with the axiom `N`. -/
abbrev EMCN.axioms : FormulaSet α := EM.axioms ∪ EC.axioms ∪ EN.axioms

/-- The logic generated by the axiom schemes `M`, `C` together with the axiom `N`. -/
abbrev EMCN : Logic α := Hilbert EMCN.axioms

instance : (EMCN (α := α)).HasAxiomM := Hilbert.hasAxiomM_of fun A B => Or.inl (Or.inl ⟨A, B, rfl⟩)
instance : (EMCN (α := α)).HasAxiomC := Hilbert.hasAxiomC_of fun A B => Or.inl (Or.inr ⟨A, B, rfl⟩)
instance : (EMCN (α := α)).HasAxiomN := Hilbert.hasAxiomN_of (Or.inr rfl)

/-! ### Logics combining `M`, `C`, `K` -/

/-- Every instance of the axiom scheme `K`. -/
abbrev EK.axioms : FormulaSet α := { Axioms.K A B | (A) (B) }

/-- The logic generated by the axiom scheme `K`. -/
abbrev EK : Logic α := Hilbert EK.axioms

instance : (EK (α := α)).HasAxiomK := Hilbert.hasAxiomK_of fun A B => ⟨A, B, rfl⟩

/-- Every instance of the axiom schemes `M` and `K`. -/
abbrev EMK.axioms : FormulaSet α := EM.axioms ∪ EK.axioms

/-- The logic generated by the axiom schemes `M` and `K`. -/
abbrev EMK : Logic α := Hilbert EMK.axioms

instance : (EMK (α := α)).HasAxiomM := Hilbert.hasAxiomM_of fun A B => Or.inl ⟨A, B, rfl⟩
instance : (EMK (α := α)).HasAxiomK := Hilbert.hasAxiomK_of fun A B => Or.inr ⟨A, B, rfl⟩

/-- Every instance of the axiom schemes `M`, `C` and `K`. -/
abbrev EMCK.axioms : FormulaSet α := EM.axioms ∪ EC.axioms ∪ EK.axioms

/-- The logic generated by the axiom schemes `M`, `C` and `K`. -/
abbrev EMCK : Logic α := Hilbert EMCK.axioms

instance : (EMCK (α := α)).HasAxiomM := Hilbert.hasAxiomM_of fun A B => Or.inl (Or.inl ⟨A, B, rfl⟩)
instance : (EMCK (α := α)).HasAxiomC := Hilbert.hasAxiomC_of fun A B => Or.inl (Or.inr ⟨A, B, rfl⟩)
instance : (EMCK (α := α)).HasAxiomK := Hilbert.hasAxiomK_of fun A B => Or.inr ⟨A, B, rfl⟩

/-! ### Logics with the reflexivity axiom `T` -/

/-- Every instance of the axiom scheme `T`. -/
abbrev ET.axioms : FormulaSet α := { Axioms.T A | (A) }

/-- The logic generated by the axiom scheme `T`. -/
abbrev ET : Logic α := Hilbert ET.axioms

instance : (ET (α := α)).HasAxiomT := Hilbert.hasAxiomT_of fun A => ⟨A, rfl⟩

/-- Every instance of the axiom schemes `M` and `T`. -/
abbrev EMT.axioms : FormulaSet α := EM.axioms ∪ ET.axioms

/-- The logic generated by the axiom schemes `M` and `T`. -/
abbrev EMT : Logic α := Hilbert EMT.axioms

instance : (EMT (α := α)).HasAxiomM := Hilbert.hasAxiomM_of fun A B => Or.inl ⟨A, B, rfl⟩
instance : (EMT (α := α)).HasAxiomT := Hilbert.hasAxiomT_of fun A => Or.inr ⟨A, rfl⟩

/-! ### Logics with the seriality axiom `D` -/

/-- Every instance of the axiom scheme `D`. -/
abbrev ED.axioms : FormulaSet α := { Axioms.D A | (A) }

/-- The logic generated by the axiom scheme `D`. -/
abbrev ED : Logic α := Hilbert ED.axioms

instance : (ED (α := α)).HasAxiomD := Hilbert.hasAxiomD_of fun A => ⟨A, rfl⟩

/-- Every instance of the axiom `N` together with the axiom scheme `D`. -/
abbrev END.axioms : FormulaSet α := EN.axioms ∪ ED.axioms

/-- The logic generated by the axiom `N` together with the axiom scheme `D`. -/
abbrev END : Logic α := Hilbert END.axioms

instance : (END (α := α)).HasAxiomN := Hilbert.hasAxiomN_of (Or.inl rfl)
instance : (END (α := α)).HasAxiomD := Hilbert.hasAxiomD_of fun A => Or.inr ⟨A, rfl⟩

/-! ### The alternative seriality axiom `P` -/

/-- The axiom `P`. -/
abbrev EP.axioms : FormulaSet α := {Axioms.P}

/-- The logic generated by the axiom `P`. -/
abbrev EP : Logic α := Hilbert EP.axioms

instance : (EP (α := α)).HasAxiomP := Hilbert.hasAxiomP_of rfl

/-! ### Logics with the symmetry axiom `B` -/

/-- Every instance of the axiom scheme `B`. -/
abbrev EB.axioms : FormulaSet α := { Axioms.B A | (A) }

/-- The logic generated by the axiom scheme `B`. -/
abbrev EB : Logic α := Hilbert EB.axioms

instance : (EB (α := α)).HasAxiomB := Hilbert.hasAxiomB_of fun A => ⟨A, rfl⟩

/-- Every instance of the axiom schemes `T` and `B`. -/
abbrev ETB.axioms : FormulaSet α := ET.axioms ∪ EB.axioms

/-- The logic generated by the axiom schemes `T` and `B`. -/
abbrev ETB : Logic α := Hilbert ETB.axioms

instance : (ETB (α := α)).HasAxiomT := Hilbert.hasAxiomT_of fun A => Or.inl ⟨A, rfl⟩
instance : (ETB (α := α)).HasAxiomB := Hilbert.hasAxiomB_of fun A => Or.inr ⟨A, rfl⟩

/-- Every instance of the axiom `N` together with the axiom schemes `T` and `B`. -/
abbrev ENTB.axioms : FormulaSet α := EN.axioms ∪ ET.axioms ∪ EB.axioms

/-- The logic generated by the axiom `N` together with the axiom schemes `T` and `B`. -/
abbrev ENTB : Logic α := Hilbert ENTB.axioms

instance : (ENTB (α := α)).HasAxiomN := Hilbert.hasAxiomN_of (Or.inl (Or.inl rfl))
instance : (ENTB (α := α)).HasAxiomT := Hilbert.hasAxiomT_of fun A => Or.inl (Or.inr ⟨A, rfl⟩)
instance : (ENTB (α := α)).HasAxiomB := Hilbert.hasAxiomB_of fun A => Or.inr ⟨A, rfl⟩

/-! ### Logics with the transitivity axiom `Four` -/

/-- Every instance of the axiom scheme `Four`. -/
abbrev E4.axioms : FormulaSet α := { Axioms.Four A | (A) }

/-- The logic generated by the axiom scheme `Four`. -/
abbrev E4 : Logic α := Hilbert E4.axioms

instance : (E4 (α := α)).HasAxiomFour := Hilbert.hasAxiomFour_of fun A => ⟨A, rfl⟩

/-- Every instance of the axiom `N` together with the axiom scheme `Four`. -/
abbrev EN4.axioms : FormulaSet α := EN.axioms ∪ E4.axioms

/-- The logic generated by the axiom `N` together with the axiom scheme `Four`. -/
abbrev EN4 : Logic α := Hilbert EN4.axioms

instance : (EN4 (α := α)).HasAxiomN := Hilbert.hasAxiomN_of (Or.inl rfl)
instance : (EN4 (α := α)).HasAxiomFour := Hilbert.hasAxiomFour_of fun A => Or.inr ⟨A, rfl⟩

/-- Every instance of the axiom schemes `T` and `Four`. -/
abbrev ET4.axioms : FormulaSet α := ET.axioms ∪ E4.axioms

/-- The logic generated by the axiom schemes `T` and `Four`. -/
abbrev ET4 : Logic α := Hilbert ET4.axioms

instance : (ET4 (α := α)).HasAxiomT := Hilbert.hasAxiomT_of fun A => Or.inl ⟨A, rfl⟩
instance : (ET4 (α := α)).HasAxiomFour := Hilbert.hasAxiomFour_of fun A => Or.inr ⟨A, rfl⟩

/-- Every instance of the axiom `N` together with the axiom schemes `T` and `Four`. -/
abbrev ENT4.axioms : FormulaSet α := EN.axioms ∪ ET.axioms ∪ E4.axioms

/-- The logic generated by the axiom `N` together with the axiom schemes `T` and `Four`. -/
abbrev ENT4 : Logic α := Hilbert ENT4.axioms

instance : (ENT4 (α := α)).HasAxiomN := Hilbert.hasAxiomN_of (Or.inl (Or.inl rfl))
instance : (ENT4 (α := α)).HasAxiomT := Hilbert.hasAxiomT_of fun A => Or.inl (Or.inr ⟨A, rfl⟩)
instance : (ENT4 (α := α)).HasAxiomFour := Hilbert.hasAxiomFour_of fun A => Or.inr ⟨A, rfl⟩

/-- Every instance of the axiom `N` together with the axiom schemes `D` and `Four`. -/
abbrev END4.axioms : FormulaSet α := EN.axioms ∪ ED.axioms ∪ E4.axioms

/-- The logic generated by the axiom `N` together with the axiom schemes `D` and `Four`. -/
abbrev END4 : Logic α := Hilbert END4.axioms

instance : (END4 (α := α)).HasAxiomN := Hilbert.hasAxiomN_of (Or.inl (Or.inl rfl))
instance : (END4 (α := α)).HasAxiomD := Hilbert.hasAxiomD_of fun A => Or.inl (Or.inr ⟨A, rfl⟩)
instance : (END4 (α := α)).HasAxiomFour := Hilbert.hasAxiomFour_of fun A => Or.inr ⟨A, rfl⟩

/-- Every instance of the axiom schemes `M`, `T` and `Four`. -/
abbrev EMT4.axioms : FormulaSet α := EM.axioms ∪ ET.axioms ∪ E4.axioms

/-- The logic generated by the axiom schemes `M`, `T` and `Four`. -/
abbrev EMT4 : Logic α := Hilbert EMT4.axioms

instance : (EMT4 (α := α)).HasAxiomM := Hilbert.hasAxiomM_of fun A B => Or.inl (Or.inl ⟨A, B, rfl⟩)
instance : (EMT4 (α := α)).HasAxiomT := Hilbert.hasAxiomT_of fun A => Or.inl (Or.inr ⟨A, rfl⟩)
instance : (EMT4 (α := α)).HasAxiomFour := Hilbert.hasAxiomFour_of fun A => Or.inr ⟨A, rfl⟩

/-- Every instance of the axiom scheme `M`, the axiom `N` together with the axiom
schemes `T` and `Four`. -/
abbrev EMNT4.axioms : FormulaSet α := EM.axioms ∪ EN.axioms ∪ ET.axioms ∪ E4.axioms

/-- The logic generated by the axiom scheme `M`, the axiom `N` together with the axiom schemes `T`
and `Four`. -/
abbrev EMNT4 : Logic α := Hilbert EMNT4.axioms

instance : (EMNT4 (α := α)).HasAxiomM :=
  Hilbert.hasAxiomM_of fun A B => Or.inl (Or.inl (Or.inl ⟨A, B, rfl⟩))
instance : (EMNT4 (α := α)).HasAxiomN := Hilbert.hasAxiomN_of (Or.inl (Or.inl (Or.inr rfl)))
instance : (EMNT4 (α := α)).HasAxiomT := Hilbert.hasAxiomT_of fun A => Or.inl (Or.inr ⟨A, rfl⟩)
instance : (EMNT4 (α := α)).HasAxiomFour := Hilbert.hasAxiomFour_of fun A => Or.inr ⟨A, rfl⟩

/-- Every instance of the axiom schemes `M`, `C` and `Four`. -/
abbrev EMC4.axioms : FormulaSet α := EM.axioms ∪ EC.axioms ∪ E4.axioms

/-- The logic generated by the axiom schemes `M`, `C` and `Four`. -/
abbrev EMC4 : Logic α := Hilbert EMC4.axioms

instance : (EMC4 (α := α)).HasAxiomM := Hilbert.hasAxiomM_of fun A B => Or.inl (Or.inl ⟨A, B, rfl⟩)
instance : (EMC4 (α := α)).HasAxiomC := Hilbert.hasAxiomC_of fun A B => Or.inl (Or.inr ⟨A, B, rfl⟩)
instance : (EMC4 (α := α)).HasAxiomFour := Hilbert.hasAxiomFour_of fun A => Or.inr ⟨A, rfl⟩

/-- Every instance of the axiom schemes `M`, `C`, the axiom `N` together with the
axiom scheme `Four`. -/
abbrev EMCN4.axioms : FormulaSet α := EM.axioms ∪ EC.axioms ∪ EN.axioms ∪ E4.axioms

/-- The logic generated by the axiom schemes `M`, `C`, the axiom `N` together with the axiom
scheme `Four`. -/
abbrev EMCN4 : Logic α := Hilbert EMCN4.axioms

instance : (EMCN4 (α := α)).HasAxiomM :=
  Hilbert.hasAxiomM_of fun A B => Or.inl (Or.inl (Or.inl ⟨A, B, rfl⟩))
instance : (EMCN4 (α := α)).HasAxiomC :=
  Hilbert.hasAxiomC_of fun A B => Or.inl (Or.inl (Or.inr ⟨A, B, rfl⟩))
instance : (EMCN4 (α := α)).HasAxiomN := Hilbert.hasAxiomN_of (Or.inl (Or.inr rfl))
instance : (EMCN4 (α := α)).HasAxiomFour := Hilbert.hasAxiomFour_of fun A => Or.inr ⟨A, rfl⟩

/-! ### Logics with the euclideanness axiom `Five` -/

/-- Every instance of the axiom scheme `Five`. -/
abbrev E5.axioms : FormulaSet α := { Axioms.Five A | (A) }

/-- The logic generated by the axiom scheme `Five`. -/
abbrev E5 : Logic α := Hilbert E5.axioms

instance : (E5 (α := α)).HasAxiomFive := Hilbert.hasAxiomFive_of fun A => ⟨A, rfl⟩

/-- Every instance of the axiom schemes `T` and `Five`. -/
abbrev ET5.axioms : FormulaSet α := ET.axioms ∪ E5.axioms

/-- The logic generated by the axiom schemes `T` and `Five`. -/
abbrev ET5 : Logic α := Hilbert ET5.axioms

instance : (ET5 (α := α)).HasAxiomT := Hilbert.hasAxiomT_of fun A => Or.inl ⟨A, rfl⟩
instance : (ET5 (α := α)).HasAxiomFive := Hilbert.hasAxiomFive_of fun A => Or.inr ⟨A, rfl⟩

/-! ### Coincidences -/

/-- The axiom scheme `C` is redundant over `M` and `K`. -/
theorem EMK_eq_EMCK : (EMK (α := α)) = EMCK := by
  apply Set.Subset.antisymm
  · apply Hilbert.subset_of_subset_axioms
    rintro A (hM | hK)
    · exact Or.inl (Or.inl hM)
    · exact Or.inr hK
  · apply Hilbert.subset_of_provable_axioms
    rintro A ((⟨B, C, rfl⟩ | ⟨B, C, rfl⟩) | ⟨B, C, rfl⟩) <;>
      first | exact Logic.axiomM! | exact Logic.axiomC! | exact Logic.axiomK!

/-- The axiom `N` is redundant over `T` and `B`. -/
theorem ETB_eq_ENTB : (ETB (α := α)) = ENTB := by
  apply Set.Subset.antisymm
  · apply Hilbert.subset_of_subset_axioms
    rintro A (hT | hB)
    · exact Or.inl (Or.inr hT)
    · exact Or.inr hB
  · apply Hilbert.subset_of_provable_axioms
    rintro A ((rfl | ⟨B, rfl⟩) | ⟨B, rfl⟩) <;>
      first | exact Logic.axiomN! | exact Logic.axiomT! | exact Logic.axiomB!

end
