module

public import Neighborhood.Hilbert.Logic.«0»
public import Neighborhood.Hilbert.Logic.«1»
public import Neighborhood.Hilbert.Logic.«2»
public import Neighborhood.Hilbert.Logic.«3»

/-!
# The classical non-normal modal logics between `LogicE` and `LogicEMCNT5`

Definitions of the classical modal logics by their Hilbert axiomatisations, each given as the
`Hilbert` system generated by every instance of the named axiom schemes.

Besides `LogicEK`, `LogicEMK`, `LogicEMCK` and `LogicEP`, the logics form a grid: each of the
eight classical bases `E`, `EM`, `EC`, `EN`, `EMC`, `EMN`, `ECN`, `EMCN` is extended by one of
the fifteen axiom combinations of `T`, `D`, `B`, `4`, `5` that axiomatise the fifteen distinct
normal modal logics of the standard cube over `K`: `∅`, `T`, `D`, `B`, `4`, `5`, `TB`, `T4`,
`T5`, `DB`, `D4`, `D5`, `D45`, `45`, `B4`.  Over the weaker classical bases, combinations that
coincide over `K` need not coincide, so all fifteen are taken as primitive definitions.
-/

@[expose] public section

variable {α : Type u}

abbrev LogicEMCNP : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.P }
instance : (@LogicEMCNP α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCNP α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCNP α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCNP α).HasAxiomP := Hilbert.hasAxiomP_of $ by grind;

abbrev LogicEMNT4 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicEMNT4 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMNT4 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMNT4 α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicEMNT4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicEMCN4 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.Four A | (A) }
instance : (@LogicEMCN4 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCN4 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCN4 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCN4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicEMCNT : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.T A | (A) }
instance : (@LogicEMCNT α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCNT α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCNT α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCNT α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;

abbrev LogicEMCND : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) }
instance : (@LogicEMCND α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCND α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCND α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCND α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;

abbrev LogicEMCNB : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.B A | (A) }
instance : (@LogicEMCNB α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCNB α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCNB α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCNB α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;

abbrev LogicEMCN5 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMCN5 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCN5 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCN5 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCN5 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMCTB : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.B A | (A) }
instance : (@LogicEMCTB α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCTB α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCTB α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicEMCTB α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;

abbrev LogicEMNTB : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.B A | (A) }
instance : (@LogicEMNTB α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMNTB α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMNTB α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicEMNTB α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;

abbrev LogicECNTB : Logic α := Hilbert $
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.B A | (A) }
instance : (@LogicECNTB α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicECNTB α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicECNTB α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicECNTB α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;

abbrev LogicEMCNTB : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.B A | (A) }
instance : (@LogicEMCNTB α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCNTB α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCNTB α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCNTB α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicEMCNTB α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;

abbrev LogicEMCT4 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicEMCT4 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCT4 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCT4 α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicEMCT4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicECNT4 : Logic α := Hilbert $
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicECNT4 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicECNT4 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicECNT4 α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicECNT4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicEMCNT4 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicEMCNT4 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCNT4 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCNT4 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCNT4 α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicEMCNT4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicEMCT5 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMCT5 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCT5 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCT5 α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicEMCT5 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMNT5 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMNT5 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMNT5 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMNT5 α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicEMNT5 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicECNT5 : Logic α := Hilbert $
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicECNT5 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicECNT5 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicECNT5 α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicECNT5 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMCNT5 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.T A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMCNT5 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCNT5 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCNT5 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCNT5 α).HasAxiomT := Hilbert.hasAxiomT_of $ by grind;
instance : (@LogicEMCNT5 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMCDB : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.B A | (A) }
instance : (@LogicEMCDB α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCDB α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCDB α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMCDB α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;

abbrev LogicEMNDB : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.B A | (A) }
instance : (@LogicEMNDB α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMNDB α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMNDB α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMNDB α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;

abbrev LogicECNDB : Logic α := Hilbert $
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.B A | (A) }
instance : (@LogicECNDB α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicECNDB α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicECNDB α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicECNDB α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;

abbrev LogicEMCNDB : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.B A | (A) }
instance : (@LogicEMCNDB α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCNDB α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCNDB α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCNDB α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMCNDB α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;

abbrev LogicEMCD4 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicEMCD4 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCD4 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCD4 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMCD4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicEMND4 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicEMND4 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMND4 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMND4 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMND4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicECND4 : Logic α := Hilbert $
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicECND4 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicECND4 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicECND4 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicECND4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicEMCND4 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicEMCND4 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCND4 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCND4 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCND4 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMCND4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicEMCD5 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMCD5 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCD5 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCD5 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMCD5 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMND5 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMND5 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMND5 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMND5 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMND5 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicECND5 : Logic α := Hilbert $
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicECND5 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicECND5 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicECND5 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicECND5 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMCND5 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMCND5 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCND5 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCND5 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCND5 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMCND5 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMD45 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMD45 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMD45 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMD45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicEMD45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicECD45 : Logic α := Hilbert $
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicECD45 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicECD45 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicECD45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicECD45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEND45 : Logic α := Hilbert $
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEND45 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEND45 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEND45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicEND45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMCD45 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMCD45 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCD45 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCD45 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMCD45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicEMCD45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMND45 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMND45 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMND45 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMND45 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMND45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicEMND45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicECND45 : Logic α := Hilbert $
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicECND45 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicECND45 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicECND45 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicECND45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicECND45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMCND45 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.D A | (A) } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMCND45 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind (instances := 4000);
instance : (@LogicEMCND45 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind (instances := 4000);
instance : (@LogicEMCND45 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCND45 α).HasAxiomD := Hilbert.hasAxiomD_of $ by grind;
instance : (@LogicEMCND45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicEMCND45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMC45 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMC45 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMC45 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMC45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicEMC45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMN45 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMN45 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMN45 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMN45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicEMN45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicECN45 : Logic α := Hilbert $
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicECN45 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicECN45 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicECN45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicECN45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMCN45 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.Four A | (A) } ∪
  { Axioms.Five A | (A) }
instance : (@LogicEMCN45 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCN45 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCN45 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCN45 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;
instance : (@LogicEMCN45 α).HasAxiomFive := Hilbert.hasAxiomFive_of $ by grind;

abbrev LogicEMCB4 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.B A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicEMCB4 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCB4 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCB4 α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;
instance : (@LogicEMCB4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicEMNB4 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.B A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicEMNB4 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMNB4 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMNB4 α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;
instance : (@LogicEMNB4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicECNB4 : Logic α := Hilbert $
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.B A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicECNB4 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicECNB4 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicECNB4 α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;
instance : (@LogicECNB4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

abbrev LogicEMCNB4 : Logic α := Hilbert $
  { Axioms.M A B | (A) (B) } ∪
  { Axioms.C A B | (A) (B) } ∪
  { Axioms.N } ∪
  { Axioms.B A | (A) } ∪
  { Axioms.Four A | (A) }
instance : (@LogicEMCNB4 α).HasAxiomM := Hilbert.hasAxiomM_of $ by grind;
instance : (@LogicEMCNB4 α).HasAxiomC := Hilbert.hasAxiomC_of $ by grind;
instance : (@LogicEMCNB4 α).HasAxiomN := Hilbert.hasAxiomN_of $ by grind;
instance : (@LogicEMCNB4 α).HasAxiomB := Hilbert.hasAxiomB_of $ by grind;
instance : (@LogicEMCNB4 α).HasAxiomFour := Hilbert.hasAxiomFour_of $ by grind;

end
