module

public import Neighborhood.Semantics.Hilbert
public import Neighborhood.Semantics.Completeness
public import Neighborhood.Semantics.AxiomC
public import Neighborhood.Semantics.AxiomM
public import Neighborhood.Semantics.AxiomGeach
public import Neighborhood.Semantics.AxiomP
public import Neighborhood.Hilbert.Logics
import Mathlib.Tactic.FinCases

/-!
# The neighborhood logic `LogicE`

Soundness, consistency and completeness of `LogicE`, the weakest classical modal logic, with
respect to all neighborhood frames, and its strict inclusion in `LogicEM`, `LogicEC`, `LogicEN`,
`LogicEK`, `LogicED`, `LogicEP` and `LogicEB`.

Also defines two auxiliary countermodels, `Frame.simple_whitehole` and
`Frame.trivial_nontransitive`, reused by several other neighborhood logics.
-/

@[expose] public section

variable {α : Type u} {A : Formula α}

@[simp]
lemma Set.inter_eq_univ {s t : Set α} : s ∩ t = Set.univ ↔ s = Set.univ ∧ t = Set.univ := by
  simpa using Set.sInter_eq_univ (S := ({s, t} : Set (Set α)))

/-! ### Auxiliary countermodels -/

/-- The one-world frame whose only world has no neighborhood at all. -/
abbrev Frame.simple_whitehole : Frame Unit := ⟨fun _ => ∅⟩

@[simp]
lemma Frame.simple_whitehole.not_valid_axiomN :
    ¬Frame.simple_whitehole ⊧ (Axioms.N : Formula α) :=
  Frame.Validate.not_of_exists_valuation_world
    ⟨fun _ => ∅, (), by simp [NotForces, Forces, Frame.box]⟩

/-- A reflexive, monotonic and regular frame on two worlds that is not transitive. -/
abbrev Frame.trivial_nontransitive : Frame (Fin 2) :=
  ⟨fun w => match w with | 0 => ∅ | 1 => {Set.univ}⟩

instance : Frame.trivial_nontransitive.IsRegular where
  regular X Y x hx := by fin_cases x <;> simp_all [Frame.box, Frame.trivial_nontransitive]

instance : Frame.trivial_nontransitive.IsMonotonic where
  mono X Y x := by fin_cases x <;> simp [Frame.box, Frame.trivial_nontransitive]

instance : Frame.trivial_nontransitive.IsReflexive where
  refl X x := by fin_cases x <;> simp_all [Frame.box, Frame.trivial_nontransitive]

lemma Frame.trivial_nontransitive.not_isTransitive :
    ¬Frame.trivial_nontransitive.IsTransitive := by
  intro hC
  have h := hC.trans Set.univ
    (show (1 : Fin 2) ∈ Frame.trivial_nontransitive.box Set.univ by simp [Frame.box])
  simp [Frame.box, Set.eq_univ_iff_forall] at h

lemma Frame.trivial_nontransitive.not_valid_axiomFour :
    ¬Frame.trivial_nontransitive ⊧ (Axioms.Four (.atom 0) : Formula ℕ) :=
  fun h => Frame.trivial_nontransitive.not_isTransitive (isTransitive_of_valid_axiomFour h)

/-! ### Soundness, consistency and completeness -/

/-- `LogicE` is sound with respect to every neighborhood frame. -/
theorem LogicE.sound (h : A ∈ LogicE (α := α)) {κ} [Nonempty κ] (F : Frame κ) : F ⊧ A :=
  Hilbert.sound (fun B hB => by simp at hB) h

instance : (LogicE (α := α)).Consistent :=
  Hilbert.consistent_of (F := Frame.simple_blackhole) (fun B hB => by simp at hB)

variable [DecidableEq α]

/-- `LogicE` is complete with respect to all neighborhood frames. -/
theorem LogicE.complete (h : ∀ {κ : Type u} [Nonempty κ] (F : Frame κ), F ⊧ A) :
    A ∈ LogicE (α := α) :=
  (basicCanonicity LogicE).mem_of_valid
    (h (basicCanonicity LogicE).toModel.toFrame (basicCanonicity LogicE).toModel.Val)

/-! ### Strict inclusion in the logics generated by a single axiom -/

theorem LogicE_ssubset_LogicEM : (@LogicE ℕ) ⊂ LogicEM := by
  constructor
  · exact Hilbert.subset_of_subset_axioms (Set.empty_subset _)
  · intro h
    have hM : Axioms.M (.atom 0) (.atom 1) ∈ (@LogicE ℕ) := h (ProvableHilbert.axm ⟨_, _, rfl⟩)
    let M : Model (Fin 3) ℕ :=
      ⟨⟨fun w => match w with
        | 0 => {{1}}
        | 1 => {{0}, {0, 1}}
        | 2 => {{0}, {1, 2}}⟩,
       fun a => match a with
        | 0 => {0, 1}
        | 1 => {1, 2}
        | _ => Set.univ⟩
    have h0 := LogicE.sound hM M.toFrame M.Val 0
    simp [M, Forces, Frame.box, Set.ext_iff] at h0
    grind

theorem LogicE_ssubset_LogicEC : (@LogicE ℕ) ⊂ LogicEC := by
  constructor
  · exact Hilbert.subset_of_subset_axioms (Set.empty_subset _)
  · intro h
    have hC : Axioms.C (.atom 0) (.atom 1) ∈ (@LogicE ℕ) := h (ProvableHilbert.axm ⟨_, _, rfl⟩)
    let M : Model (Fin 2) ℕ :=
      ⟨⟨fun w => match w with
        | 0 => {{0}, {1}}
        | 1 => {∅}⟩,
       fun a => match a with
        | 0 => {0}
        | 1 => {1}
        | _ => Set.univ⟩
    have h0 := LogicE.sound hC M.toFrame M.Val 0
    simp [M, Forces, Frame.box, Set.ext_iff] at h0

theorem LogicE_ssubset_LogicEN : (@LogicE ℕ) ⊂ LogicEN := by
  constructor
  · exact Hilbert.subset_of_subset_axioms (Set.empty_subset _)
  · intro h
    have hN : (Axioms.N : Formula ℕ) ∈ (@LogicE ℕ) := h (ProvableHilbert.axm rfl)
    exact Frame.simple_whitehole.not_valid_axiomN (LogicE.sound hN Frame.simple_whitehole)

theorem LogicE_ssubset_LogicEK : (@LogicE ℕ) ⊂ LogicEK := by
  constructor
  · exact Hilbert.subset_of_subset_axioms (Set.empty_subset _)
  · intro h
    have hK : Axioms.K (.atom 0) (.atom 1) ∈ (@LogicE ℕ) := h (ProvableHilbert.axm ⟨_, _, rfl⟩)
    let M : Model (Fin 3) ℕ :=
      ⟨⟨fun w => match w with
        | 0 => {{0}, {0, 1, 2}}
        | 1 => ∅
        | 2 => ∅⟩,
       fun a => match a with
        | 0 => {0}
        | 1 => {0, 1}
        | _ => Set.univ⟩
    have h0 := LogicE.sound hK M.toFrame M.Val 0
    simp [M, Forces, Frame.box, Set.ext_iff] at h0
    revert h0
    decide

theorem LogicE_ssubset_LogicED : (@LogicE ℕ) ⊂ LogicED := by
  constructor
  · exact Hilbert.subset_of_subset_axioms (Set.empty_subset _)
  · intro h
    have hD : Axioms.D (.atom 0) ∈ (@LogicE ℕ) := h (ProvableHilbert.axm ⟨_, rfl⟩)
    have hS : (⟨fun w => match w with | 0 => {{0}} | 1 => Set.univ⟩ : Frame (Fin 2)).IsSerial :=
      isSerial_of_valid_axiomD (LogicE.sound hD _)
    have := hS.serial {1} (show (1 : Fin 2) ∈ _ by simp [Frame.box])
    simp [Frame.dia, Frame.box] at this

theorem LogicE_ssubset_LogicEP : (@LogicE ℕ) ⊂ LogicEP := by
  constructor
  · exact Hilbert.subset_of_subset_axioms (Set.empty_subset _)
  · intro h
    have hP : (Axioms.P : Formula ℕ) ∈ (@LogicE ℕ) := h (ProvableHilbert.axm rfl)
    have := notContainsEmpty_of_valid_axiomP
      (F := (⟨fun _ => {∅}⟩ : Frame (Fin 1))) (LogicE.sound hP _)
    simpa using this.not_contains_empty (x := 0)

theorem LogicE_ssubset_LogicEB : (@LogicE ℕ) ⊂ LogicEB := by
  constructor
  · exact Hilbert.subset_of_subset_axioms (Set.empty_subset _)
  · intro h
    have hB : Axioms.B (.atom 0) ∈ (@LogicE ℕ) := h (ProvableHilbert.axm ⟨_, rfl⟩)
    have hS : Frame.simple_whitehole.IsSymmetric :=
      isSymmetric_of_valid_axiomB (LogicE.sound hB _)
    have := hS.symm {()} (show () ∈ _ by simp)
    simp [Frame.box] at this

end
