module

public import Neighborhood.Semantics.Hilbert
public import Neighborhood.Semantics.Completeness
public import Neighborhood.Semantics.AxiomC
public import Neighborhood.Semantics.AxiomM
public import Neighborhood.Semantics.AxiomGeach
public import Neighborhood.Semantics.AxiomP
public import Neighborhood.Hilbert.Logics

/-!
# The neighborhood logic `LogicE`

Soundness, consistency and completeness of `LogicE`, the weakest classical modal logic, with
respect to all neighborhood frames, and its strict inclusion in `LogicEM`, `LogicEC`, `LogicEN`,
`LogicEK`, `LogicED`, `LogicEP` and `LogicEB`.

Also defines two auxiliary countermodels, `Frame.simple_whitehole` and
`Frame.trivial_nontransitive`, reused by several other neighborhood logics.
-/

@[expose] public section

@[simp]
lemma Set.inter_eq_univ {s t : Set α} : s ∩ t = Set.univ ↔ s = Set.univ ∧ t = Set.univ := by
  simpa using Set.sInter_eq_univ (s := ({s, t} : Set (Set α)))

/-! ### Auxiliary countermodels -/

/-- The one-world frame whose only world has no neighborhood at all. -/
abbrev Frame.simple_whitehole : Frame Unit := ⟨fun _ => ∅⟩

@[simp]
lemma Frame.simple_whitehole.not_valid_axiomN {α : Type v} :
    ¬Frame.simple_whitehole ⊧ (Axioms.N : Formula α) :=
  Frame.Validate.not_of_exists_valuation_world
    ⟨fun _ => ∅, (), by simp [NotForces, Forces, Frame.box]⟩

/-- A reflexive, monotonic and regular frame on two worlds that is not transitive. -/
abbrev Frame.trivial_nontransitive : Frame (Fin 2) :=
  ⟨fun w => match w with | 0 => ∅ | 1 => {Set.univ}⟩

instance : Frame.trivial_nontransitive.IsRegular where
  regular X Y x hx := by fin_cases x <;> simp_all [Frame.box, Frame.trivial_nontransitive]

instance : Frame.trivial_nontransitive.IsMonotonic where
  mono X Y x := by fin_cases x <;> simp [Frame.box, Frame.trivial_nontransitive]

instance : Frame.trivial_nontransitive.IsReflexive where
  refl X x := by fin_cases x <;> simp_all [Frame.box, Frame.trivial_nontransitive]

lemma Frame.trivial_nontransitive.not_isTransitive :
    ¬Frame.trivial_nontransitive.IsTransitive := by
  intro hC
  have h := hC.trans (X := Set.univ) (x := (1 : Fin 2))
  simp [Frame.box, Frame.trivial_nontransitive] at h

lemma Frame.trivial_nontransitive.not_valid_axiomFour :
    ¬Frame.trivial_nontransitive ⊧ (Axioms.Four (.atom 0) : Formula ℕ) :=
  fun h => Frame.trivial_nontransitive.not_isTransitive (isTransitive_of_valid_axiomFour h)

/-! ### Soundness, consistency and completeness -/

variable {α : Type u} {A : Formula α}

/-- `LogicE` is sound with respect to every neighborhood frame. -/
theorem LogicE.sound (h : A ∈ LogicE (α := α)) {κ} [Nonempty κ] (F : Frame κ) : F ⊧ A :=
  Hilbert.sound (fun B hB => absurd hB (Set.not_mem_empty B)) h

instance : (LogicE (α := α)).Consistent :=
  Hilbert.consistent_of (F := Frame.simple_blackhole) (fun B hB => absurd hB (Set.not_mem_empty B))

variable [DecidableEq α]

/-- `LogicE` is complete with respect to all neighborhood frames. -/
theorem LogicE.complete (h : ∀ {κ : Type} [Nonempty κ] (F : Frame κ), F ⊧ A) :
    A ∈ LogicE (α := α) :=
  (basicCanonicity LogicE).mem_of_valid (h (basicCanonicity LogicE).toModel.toFrame)

/-! ### Strict inclusion in the logics generated by a single axiom -/

theorem LogicE_ssubset_LogicEM : (LogicE (α := ℕ)) ⊂ LogicEM :=
  ⟨Hilbert.subset_of_subset_axioms (Set.empty_subset _), by
    intro h
    have hM : Axioms.M (.atom 0) (.atom 1) ∈ LogicEM := by simp
    have hM' : Axioms.M (.atom 0) (.atom 1) ∈ LogicE (α := ℕ) := h hM
    let M : Model (Fin 3) ℕ :=
      ⟨⟨fun w => match w with
        | 0 => {{1}}
        | 1 => {{0}, {0, 1}}
        | 2 => {{0}, {1, 2}}⟩,
       fun w => match w with
        | 0 => {0, 1}
        | 1 => {1, 2}
        | 2 => Set.univ⟩
    exact absurd (M.Validate.mdp (LogicE.sound hM' M.toFrame M.Val) (fun x => by fin_cases x <;> grind))
      (by fin_cases (0 : Fin 3) <;> grind)⟩

end
